import { PAYMENT_METHOD_LABELS } from '@/types/database';
import './SummaryReceipt.css';

interface SummaryReceiptProps {
  date: string;
  data: {
    totalSales: number;
    totalOrders: number;
    totalItems: number;
    paymentBreakdown: Record<string, number>;
    products: { item_name: string; total_quantity: number; total_revenue: number }[];
  };
}

export function SummaryReceipt({ date, data }: SummaryReceiptProps) {
  const formattedDate = new Date(`${date}T00:00:00`).toLocaleDateString('en-PH', {
    weekday: 'long', month: 'long', day: 'numeric', year: 'numeric',
  });

  const printedAt = new Date().toLocaleString('en-PH', {
    month: '2-digit', day: '2-digit', year: 'numeric',
    hour: '2-digit', minute: '2-digit', hour12: true,
  });

  return (
    <div
      id="summary-receipt"
      className="receipt-root"
      style={{ display: 'none' }}
    >
      <div className="receipt-paper">
        <div className="receipt-inner">
          {/* Store Header */}
          <div className="receipt-center">
            <div className="receipt-store-name">Cafe Maestro</div>
            <div className="receipt-store-sub">Santa Rosa, Laguna</div>
          </div>

          <hr className="receipt-divider" />

          {/* Meta */}
          <div className="receipt-meta-row">
            <span className="receipt-meta-label">Date</span>
            <span>{formattedDate}</span>
          </div>
          <div className="receipt-meta-row">
            <span className="receipt-meta-label">Printed</span>
            <span>{printedAt}</span>
          </div>
          <div className="receipt-meta-row">
            <span className="receipt-meta-label">Report</span>
            <span>Daily Summary</span>
          </div>

          <hr className="receipt-divider" />

          {/* Stats */}
          <div className="receipt-stats">
            <div className="receipt-stat">
              <div className="receipt-stat-val">PHP {data.totalSales.toFixed(2)}</div>
              <div className="receipt-stat-lbl">Total Sales</div>
            </div>
            <div className="receipt-stat">
              <div className="receipt-stat-val">{data.totalOrders}</div>
              <div className="receipt-stat-lbl">Orders</div>
            </div>
            <div className="receipt-stat">
              <div className="receipt-stat-val">{data.totalItems}</div>
              <div className="receipt-stat-lbl">Items Sold</div>
            </div>
          </div>

          <hr className="receipt-divider" />

          {/* Products */}
          <div className="receipt-section-title">Products Sold</div>
          {data.products.map((product, index) => (
            <div key={product.item_name} className="receipt-item-row">
              <div className="receipt-item-name">
                {index === 0 && <span className="receipt-item-badge">#1</span>}
                {product.item_name}
              </div>
              <div className="receipt-item-qty">x{product.total_quantity}</div>
              <div className="receipt-item-rev">PHP {product.total_revenue.toFixed(2)}</div>
            </div>
          ))}

          <hr className="receipt-divider" />

          {/* Total */}
          <div className="receipt-total-row">
            <span>TOTAL ({data.totalItems} items)</span>
            <span>PHP {data.totalSales.toFixed(2)}</span>
          </div>

          <hr className="receipt-divider" />

          {/* Payment Breakdown */}
          <div className="receipt-section-title">Payment Breakdown</div>
          <div className="receipt-payment-grid">
            {Object.entries(data.paymentBreakdown).map(([method, amount]) => (
              <div key={method} className="receipt-payment-box">
                <div className="receipt-payment-method">
                  {PAYMENT_METHOD_LABELS[method as keyof typeof PAYMENT_METHOD_LABELS] ?? method}
                </div>
                <div className="receipt-payment-amount">PHP {(amount as number).toFixed(2)}</div>
              </div>
            ))}
          </div>

          <hr className="receipt-divider" />

          <div className="receipt-footer">Thank you! · Generated by Cafe Maestro POS System</div>
        </div>
      </div>
    </div>
  );
}